# Generated by Django 4.2.7 on 2024-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('cam_mark_returned', 'Set book as returned.'),)},
        ),
    ]
