# Generated by Django 4.2.7 on 2024-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book cover',
            field=models.ImageField(default='catalog/book_covers/no_book_cover.png', upload_to='catalog/book_covers/', verbose_name='book_cover'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
    ]
